name: Trilar_KitPvP
main: me.imelvin.kitpvp.Kitpvp
author: [shizleshizle, iMelvin]
description: Trilar KitPvP Core
version: 0.0.1
api-version: 1.13
depend: [Trilar_Core]
commands:
  arena:
    description: Set, list or remove an arena!
  kitpvp:
    description: Place the NPC for Kit selector!