package me.imelvin.kitpvp.utils;

import java.util.ArrayList;
import java.util.HashMap;

import org.bukkit.ChatColor;
import org.bukkit.Material;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.bukkit.potion.Potion;
import org.bukkit.potion.PotionType;

import me.shizleshizle.core.utils.CI;
import me.shizleshizle.core.utils.T_ItemStack;

public class Kits {
	
	public static HashMap<String, Kit> kits = new HashMap<>();

	public enum Kit {
		TANK, PVP, NO_DEBUFF, TROLL, AXE, TROLL_2, DEBUF, INVISIBLE, STRENGTH, ARCHER, OP
	}
	
	public static void giveKit(Player p, Kit k) {
		if (k.equals(Kit.TANK)) {
			p.getInventory().clear();
			ItemStack[] items = tankkit.toArray(new ItemStack[tankkit.size()]);
			p.getInventory().setContents(items);
		} else if (k.equals(Kit.PVP)) {
			p.getInventory().clear();
			ItemStack[] items = pvpkit.toArray(new ItemStack[pvpkit.size()]);
			p.getInventory().setContents(items);
		} else if (k.equals(Kit.NO_DEBUFF)) {
			p.getInventory().clear();
			ItemStack[] items = ndefkit.toArray(new ItemStack[ndefkit.size()]);
			p.getInventory().setContents(items);
		}  else if (k.equals(Kit.TROLL)) {
			p.getInventory().clear();
			ItemStack[] items = trolkit.toArray(new ItemStack[trolkit.size()]);
			p.getInventory().setContents(items);
		} else if (k.equals(Kit.AXE)) {
			p.getInventory().clear();
			ItemStack[] items = axekit.toArray(new ItemStack[axekit.size()]);
			p.getInventory().setContents(items);
		} else if (k.equals(Kit.TROLL_2)) {
			p.getInventory().clear();
			ItemStack[] items = trollkit.toArray(new ItemStack[trollkit.size()]);
			p.getInventory().setContents(items);
		} else if (k.equals(Kit.DEBUF)) {
			p.getInventory().clear();
			ItemStack[] items = debufkit.toArray(new ItemStack[debufkit.size()]);
			p.getInventory().setContents(items);
		} else if (k.equals(Kit.INVISIBLE)) {
			p.getInventory().clear();
			ItemStack[] items = inviskit.toArray(new ItemStack[inviskit.size()]);
			p.getInventory().setContents(items);
		} else if (k.equals(Kit.STRENGTH)) {
			p.getInventory().clear();
			ItemStack[] items = strengthkit.toArray(new ItemStack[strengthkit.size()]);
			p.getInventory().setContents(items);
		} else if (k.equals(Kit.ARCHER)) {
			p.getInventory().clear();
			ItemStack[] items = archerkit.toArray(new ItemStack[archerkit.size()]);
			p.getInventory().setContents(items);
		} else if (k.equals(Kit.OP)) {
			p.getInventory().clear();
			ItemStack[] items = opkit.toArray(new ItemStack[opkit.size()]);
			p.getInventory().setContents(items);
		}
	}

	public static ArrayList<ItemStack> tankkit = new ArrayList<>(); // TANK
	public static ArrayList<ItemStack> pvpkit = new ArrayList<>(); // PVP
	public static ArrayList<ItemStack> ndefkit = new ArrayList<>(); // No Debuf
	public static ArrayList<ItemStack> trolkit = new ArrayList<>(); // Troll 1
	public static ArrayList<ItemStack> axekit = new ArrayList<>(); // Axe
	public static ArrayList<ItemStack> trollkit = new ArrayList<>(); // Troll 2
	public static ArrayList<ItemStack> debufkit = new ArrayList<>(); // Debuf
	public static ArrayList<ItemStack> inviskit = new ArrayList<>(); // Invisible
	public static ArrayList<ItemStack> strengthkit = new ArrayList<>(); // Strength
	public static ArrayList<ItemStack> archerkit = new ArrayList<>(); // Archer
	public static ArrayList<ItemStack> opkit = new ArrayList<>(); // Op

	public static void setupKits() {
		ItemStack tankhelmet = CI.createItem(Material.CHAINMAIL_HELMET, 1, -1, ChatColor.DARK_AQUA + "Tank Helmet");
		tankhelmet.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack tankchestplate = CI.createItem(Material.CHAINMAIL_CHESTPLATE, 1, -1, ChatColor.DARK_AQUA + "Tank Chestplate");
		tankchestplate.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack tankleggings = CI.createItem(Material.CHAINMAIL_LEGGINGS, 1, -1, ChatColor.DARK_AQUA + "Tank Leggings");
		tankleggings.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack tankboots = CI.createItem(Material.CHAINMAIL_BOOTS, 1, -1, ChatColor.DARK_AQUA + "Tank Boots");
		tankboots.addEnchantment(Enchantment.DURABILITY, 3);
		T_ItemStack tanksword = new T_ItemStack(CI.createItem(Material.STONE_SWORD, 1, -1, ChatColor.DARK_AQUA + "Tank Sword"));
		ItemStack tankbow = CI.createItem(Material.BOW, 1, -1, ChatColor.DARK_AQUA + "Tank Bow");
		tankbow.addEnchantment(Enchantment.ARROW_KNOCKBACK, 1);
		tankbow.addEnchantment(Enchantment.ARROW_INFINITE, 1);
		ItemStack tankarrow = CI.createItem(Material.ARROW, 1, -1, ChatColor.DARK_AQUA + "Tank Arrow");
		ItemStack tankgapple = CI.createItem(Material.GOLDEN_APPLE, 3, 0, ChatColor.DARK_AQUA + "Tank Apple");
		ItemStack tankpearl = CI.createItem(Material.ENDER_PEARL, 4, -1, ChatColor.DARK_AQUA + "Tank Pearl");
		Potion speedp = new Potion(PotionType.SPEED, 1);
		speedp.setSplash(true);
		ItemStack tankspeedp = speedp.toItemStack(1);
		tankspeedp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "Tank Speed Pot"); 
		Potion healp = new Potion(PotionType.INSTANT_HEAL, 1);
		healp.setSplash(true);
		ItemStack tankhealp = healp.toItemStack(1);
		tankhealp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "Tank Heal Pot");
		Potion regp = new Potion(PotionType.REGEN, 1);
		regp.setSplash(true);
		ItemStack tankregp = regp.toItemStack(1);
		tankregp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "Tank Regen Pot");
		tanksword.addGlow();
		tankkit.add(tanksword.toItemStack());
		tankkit.add(tankbow);
		tankkit.add(tankarrow);
		tankkit.add(tankgapple);
		tankkit.add(tankpearl);
		tankkit.add(tankspeedp);
		tankkit.add(tankhealp);
		tankkit.add(tankregp);
		tankkit.add(tankhelmet);
		tankkit.add(tankchestplate);
		tankkit.add(tankleggings);
		tankkit.add(tankboots);
		
		
		ItemStack pvphelmet = CI.createItem(Material.LEATHER_HELMET, 1, -1, ChatColor.GOLD + "PvP Helmet");
		pvphelmet.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack pvpchestplate = CI.createItem(Material.LEATHER_CHESTPLATE, 1, -1, ChatColor.GOLD + "PvP Chestplate");
		pvpchestplate.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack pvpleggings = CI.createItem(Material.LEATHER_LEGGINGS, 1, -1, ChatColor.GOLD + "PvP Leggings");
		pvpleggings.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack pvpboots = CI.createItem(Material.LEATHER_BOOTS, 1, -1, ChatColor.GOLD + "PvP Boots");
		pvpboots.addEnchantment(Enchantment.DURABILITY, 3);
		T_ItemStack pvpsword = new T_ItemStack(CI.createItem(Material.STONE_SWORD, 1, -1, ChatColor.GOLD + "PvP Sword"));
		ItemStack pvpbow = CI.createItem(Material.BOW, 1, -1, ChatColor.GOLD + "PvP Bow");
		pvpbow.addEnchantment(Enchantment.ARROW_KNOCKBACK, 1);
		pvpbow.addEnchantment(Enchantment.ARROW_INFINITE, 1);
		ItemStack pvparrow = CI.createItem(Material.ARROW, 1, -1, ChatColor.GOLD + "PvP Arrow");
		ItemStack pvpgapple = CI.createItem(Material.GOLDEN_APPLE, 3, 0, ChatColor.GOLD + "PvP Apple");
		ItemStack pvppearl = CI.createItem(Material.ENDER_PEARL, 4, -1, ChatColor.GOLD + "PvP Pearl");
		Potion speedpo = new Potion(PotionType.SPEED, 1);
		speedpo.setSplash(true);
		ItemStack pvpspeedp = speedpo.toItemStack(1);
		pvpspeedp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "Tank Speed Pot"); 
		Potion healpo = new Potion(PotionType.INSTANT_HEAL, 1);
		healpo.setSplash(true);
		ItemStack pvphealp = healpo.toItemStack(1);
		pvphealp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "Tank Heal Pot");
		Potion regpo = new Potion(PotionType.REGEN, 1);
		regpo.setSplash(true);
		ItemStack pvpregp = regpo.toItemStack(1);
		pvpregp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "Pvp Heal Pot");
		pvpsword.addGlow();
		pvpkit.add(pvpsword.toItemStack());
		pvpkit.add(pvpbow);
		pvpkit.add(pvparrow);
		pvpkit.add(pvpgapple);
		pvpkit.add(pvppearl);
		pvpkit.add(pvpspeedp);
		pvpkit.add(pvphealp);
		pvpkit.add(pvpregp);
		pvpkit.add(pvphelmet);
		pvpkit.add(pvpchestplate);
		pvpkit.add(pvpleggings);
		pvpkit.add(pvpboots);
		
		ItemStack ndefhelmet = CI.createItem(Material.LEATHER_HELMET, 1, -1, ChatColor.GOLD + "No Debuf Helmet");
		ndefhelmet.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack ndefchestplate = CI.createItem(Material.LEATHER_CHESTPLATE, 1, -1, ChatColor.GOLD + "No Debuf Chestplate");
		ndefchestplate.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack ndefleggings = CI.createItem(Material.LEATHER_LEGGINGS, 1, -1, ChatColor.GOLD + "No Debuf Leggings");
		ndefleggings.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack ndefboots = CI.createItem(Material.LEATHER_BOOTS, 1, -1, ChatColor.GOLD + "No Debuf Boots");
		ndefboots.addEnchantment(Enchantment.DURABILITY, 3);
		T_ItemStack ndefsword = new T_ItemStack(CI.createItem(Material.STONE_SWORD, 1, -1, ChatColor.GOLD + "No Debuf Sword"));
		ItemStack ndefbow = CI.createItem(Material.BOW, 1, -1, ChatColor.GOLD + "No Debuf Bow");
		ndefbow.addEnchantment(Enchantment.ARROW_KNOCKBACK, 1);
		ndefbow.addEnchantment(Enchantment.ARROW_INFINITE, 1);
		ItemStack ndefarrow = CI.createItem(Material.ARROW, 1, -1, ChatColor.GOLD + "No Debuf Arrow");
		ItemStack ndefgapple = CI.createItem(Material.GOLDEN_APPLE, 3, 0, ChatColor.GOLD + "No Debuf Apple");
		ItemStack ndefpearl = CI.createItem(Material.ENDER_PEARL, 4, -1, ChatColor.GOLD + "No Debuf Pearl");
		Potion speedpot = new Potion(PotionType.SPEED, 1);
		speedpot.setSplash(true);
		ItemStack ndefspeedp = speedpot.toItemStack(1);
		ndefspeedp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "No Debuf Speed Pot"); 
		Potion healpot = new Potion(PotionType.INSTANT_HEAL, 1);
		healpot.setSplash(true);
		ItemStack ndefhealp = healpot.toItemStack(2);
		ndefhealp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "No Debuf Heal Pot");
		Potion regpot = new Potion(PotionType.REGEN, 1);
		regpot.setSplash(true);
		ItemStack ndefregp = regpot.toItemStack(2);
		ndefregp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "No Debuf Regen Pot");
		ndefsword.addGlow();
		ndefkit.add(ndefsword.toItemStack());
		ndefkit.add(ndefbow);
		ndefkit.add(ndefarrow);
		ndefkit.add(ndefgapple);
		ndefkit.add(ndefpearl);
		ndefkit.add(ndefspeedp);
		ndefkit.add(ndefhealp);
		ndefkit.add(ndefregp);
		ndefkit.add(ndefhelmet);
		ndefkit.add(ndefchestplate);
		ndefkit.add(ndefleggings);
		ndefkit.add(ndefboots);
		
		ItemStack trolhelmet = CI.createItem(Material.LEATHER_HELMET, 1, -1, ChatColor.GOLD + "Troll Helmet");
		trolhelmet.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack trolchestplate = CI.createItem(Material.LEATHER_CHESTPLATE, 1, -1, ChatColor.GOLD + "Troll Chestplate");
		trolchestplate.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack trolleggings = CI.createItem(Material.LEATHER_LEGGINGS, 1, -1, ChatColor.GOLD + "Troll Leggings");
		trolleggings.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack trolboots = CI.createItem(Material.LEATHER_BOOTS, 1, -1, ChatColor.GOLD + "Troll Boots");
		trolboots.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack trolstick = CI.createItem(Material.STICK, 1, -1, ChatColor.GOLD + "Troll Stick");
		trolstick.addEnchantment(Enchantment.KNOCKBACK, 1);
		ItemStack trolbow = CI.createItem(Material.BOW, 1, -1, ChatColor.GOLD + "Troll Bow");
		trolbow.addEnchantment(Enchantment.ARROW_KNOCKBACK, 1);
		trolbow.addEnchantment(Enchantment.ARROW_INFINITE, 1);
		ItemStack trolarrow = CI.createItem(Material.ARROW, 1, -1, ChatColor.GOLD + "Troll Arrow");
		ItemStack trolgapple = CI.createItem(Material.GOLDEN_APPLE, 3, 0, ChatColor.GOLD + "Troll Apple");
		ItemStack trolpearl = CI.createItem(Material.ENDER_PEARL, 4, -1, ChatColor.GOLD + "Troll Pearl");
		Potion speedpoti = new Potion(PotionType.SPEED, 1);
		speedpoti.setSplash(true);
		ItemStack trolspeedp = speedpoti.toItemStack(1);
		trolspeedp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "Troll Speed Pot"); 
		Potion healpoti = new Potion(PotionType.INSTANT_HEAL, 1);
		healpoti.setSplash(true);
		ItemStack trolhealp = healpoti.toItemStack(1);
		trolhealp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "Troll Heal Pot");
		Potion regpoti = new Potion(PotionType.REGEN, 1);
		regpoti.setSplash(true);
		ItemStack trolregp = regpoti.toItemStack(1);
		trolregp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "Troll Regen Pot");
		trolkit.add(trolstick);
		trolkit.add(trolbow);
		trolkit.add(trolarrow);
		trolkit.add(trolgapple);
		trolkit.add(trolpearl);
		trolkit.add(trolspeedp);
		trolkit.add(trolhealp);
		trolkit.add(trolregp);
		trolkit.add(trolhelmet);
		trolkit.add(trolchestplate);
		trolkit.add(trolleggings);
		trolkit.add(trolboots);
		
		ItemStack axehelmet = CI.createItem(Material.GOLD_HELMET, 1, -1, ChatColor.GOLD + "Axe Helmet");
		axehelmet.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack axechestplate = CI.createItem(Material.GOLD_CHESTPLATE, 1, -1, ChatColor.GOLD + "Axe Chestplate");
		axechestplate.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack axeleggings = CI.createItem(Material.GOLD_LEGGINGS, 1, -1, ChatColor.GOLD + "Axe Leggings");
		axeleggings.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack axeboots = CI.createItem(Material.GOLD_BOOTS, 1, -1, ChatColor.GOLD + "Axe Boots");
		axeboots.addEnchantment(Enchantment.DURABILITY, 3);
		T_ItemStack axeaxe = new T_ItemStack(CI.createItem(Material.IRON_AXE, 1, -1, ChatColor.GOLD + "Axe"));
		ItemStack axebow = CI.createItem(Material.BOW, 1, -1, ChatColor.GOLD + "Axe Bow");
		axebow.addEnchantment(Enchantment.ARROW_KNOCKBACK, 1);
		axebow.addEnchantment(Enchantment.ARROW_INFINITE, 1);
		ItemStack axearrow = CI.createItem(Material.ARROW, 1, -1, ChatColor.GOLD + "Axe Arrow");
		ItemStack axegapple = CI.createItem(Material.GOLDEN_APPLE, 3, 0, ChatColor.GOLD + "Axe Apple");
		ItemStack axepearl = CI.createItem(Material.ENDER_PEARL, 4, -1, ChatColor.GOLD + "Axe Pearl");
		Potion speedpotio = new Potion(PotionType.SPEED, 1);
		speedpotio.setSplash(true);
		ItemStack axespeedp = speedpotio.toItemStack(1);
		axespeedp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "Axe Speed Pot"); 
		Potion healpotio = new Potion(PotionType.INSTANT_HEAL, 1);
		healpotio.setSplash(true);
		ItemStack axehealp = healpotio.toItemStack(1);
		axehealp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "Axe Heal Pot");
		Potion regpotio = new Potion(PotionType.REGEN, 1);
		regpotio.setSplash(true);
		ItemStack axeregp = regpotio.toItemStack(1);
		axeregp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "Axe Regen Pot");
		axeaxe.addGlow();
		axekit.add(axeaxe.toItemStack());
		axekit.add(axebow);
		axekit.add(axearrow);
		axekit.add(axegapple);
		axekit.add(axepearl);
		axekit.add(axespeedp);
		axekit.add(axehealp);
		axekit.add(axeregp);
		axekit.add(axehelmet);
		axekit.add(axechestplate);
		axekit.add(axeleggings);
		axekit.add(axeboots);
		
		ItemStack trollhelmet = CI.createItem(Material.LEATHER_HELMET, 1, -1, ChatColor.GOLD + "Troll Helmet");
		trollhelmet.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack trollchestplate = CI.createItem(Material.LEATHER_CHESTPLATE, 1, -1, ChatColor.GOLD + "Troll Chestplate");
		trollchestplate.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack trollleggings = CI.createItem(Material.LEATHER_LEGGINGS, 1, -1, ChatColor.GOLD + "Troll Leggings");
		trollleggings.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack trollboots = CI.createItem(Material.LEATHER_BOOTS, 1, -1, ChatColor.GOLD + "Troll Boots");
		trollboots.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack trollstick = CI.createItem(Material.STICK, 1, -1, ChatColor.GOLD + "Troll Stick");
		trollstick.addEnchantment(Enchantment.KNOCKBACK, 2);
		ItemStack trollbow = CI.createItem(Material.BOW, 1, -1, ChatColor.GOLD + "Troll Bow");
		trollbow.addEnchantment(Enchantment.ARROW_KNOCKBACK, 1);
		trollbow.addEnchantment(Enchantment.ARROW_INFINITE, 1);
		ItemStack trollarrow = CI.createItem(Material.ARROW, 1, -1, ChatColor.GOLD + "Troll Arrow");
		ItemStack trollgapple = CI.createItem(Material.GOLDEN_APPLE, 3, 0, ChatColor.GOLD + "Troll Apple");
		ItemStack trollpearl = CI.createItem(Material.ENDER_PEARL, 4, -1, ChatColor.GOLD + "Troll Pearl");
		Potion speedpotion = new Potion(PotionType.SPEED, 1);
		speedpotion.setSplash(true);
		ItemStack trollspeedp = speedpotion.toItemStack(1);
		trolspeedp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "Troll Speed Pot"); 
		Potion healpotion = new Potion(PotionType.INSTANT_HEAL, 1);
		healpotion.setSplash(true);
		ItemStack trollhealp = healpotion.toItemStack(1);
		trolhealp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "Troll Heal Pot");
		Potion regpotion = new Potion(PotionType.REGEN, 1);
		regpotion.setSplash(true);
		ItemStack trollregp = regpotion.toItemStack(1);
		trolregp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "Troll Regen Pot");
		trollkit.add(trollstick);
		trollkit.add(trollbow);
		trollkit.add(trollarrow);
		trollkit.add(trollgapple);
		trollkit.add(trollpearl);
		trollkit.add(trollspeedp);
		trollkit.add(trollhealp);
		trollkit.add(trollregp);
		trollkit.add(trollhelmet);
		trollkit.add(trollchestplate);
		trollkit.add(trollleggings);
		trollkit.add(trollboots);
		
		ItemStack defhelmet = CI.createItem(Material.LEATHER_HELMET, 1, -1, ChatColor.GOLD + "Debuf Helmet");
		defhelmet.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack defchestplate = CI.createItem(Material.LEATHER_CHESTPLATE, 1, -1, ChatColor.GOLD + "Debuf Chestplate");
		defchestplate.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack defleggings = CI.createItem(Material.LEATHER_LEGGINGS, 1, -1, ChatColor.GOLD + "Debuf Leggings");
		defleggings.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack defboots = CI.createItem(Material.LEATHER_BOOTS, 1, -1, ChatColor.GOLD + "Debuf Boots");
		defboots.addEnchantment(Enchantment.DURABILITY, 3);
		T_ItemStack defsword = new T_ItemStack(CI.createItem(Material.STONE_SWORD, 1, -1, ChatColor.GOLD + "Debuf Sword"));
		ItemStack defbow = CI.createItem(Material.BOW, 1, -1, ChatColor.GOLD + "Debuf Bow");
		defbow.addEnchantment(Enchantment.ARROW_KNOCKBACK, 1);
		defbow.addEnchantment(Enchantment.ARROW_INFINITE, 1);
		ItemStack defarrow = CI.createItem(Material.ARROW, 1, -1, ChatColor.GOLD + "Debuf Arrow");
		ItemStack defgapple = CI.createItem(Material.GOLDEN_APPLE, 3, 0, ChatColor.GOLD + "Debuf Apple");
		ItemStack defpearl = CI.createItem(Material.ENDER_PEARL, 4, -1, ChatColor.GOLD +  "Debuf Pearl");
		Potion speedpotionn = new Potion(PotionType.SPEED, 1);
		speedpotionn.setSplash(true);
		ItemStack defspeedp = speedpotionn.toItemStack(2);
		defspeedp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "Debuf Speed Pot"); 
		Potion healpotionn = new Potion(PotionType.INSTANT_HEAL, 1);
		healpotionn.setSplash(true);
		ItemStack defhealp = healpotionn.toItemStack(1);
		defhealp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "Debuf Heal Pot");
		Potion regpotionn = new Potion(PotionType.REGEN, 1);
		regpotionn.setSplash(true);
		ItemStack defregp = regpotionn.toItemStack(1);
		defregp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "Debuf Regen Pot");
		Potion harmpotion = new Potion(PotionType.REGEN, 1);
		harmpotion.setSplash(true);
		ItemStack defharmp = harmpotion.toItemStack(1);
		defharmp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "Debuf Harming Pot");
		defsword.addGlow();
		debufkit.add(defsword.toItemStack());
		debufkit.add(defbow);
		debufkit.add(defarrow);
		debufkit.add(defgapple);
		debufkit.add(defpearl);
		debufkit.add(defspeedp);
		debufkit.add(defhealp);
		debufkit.add(defregp);
		debufkit.add(defharmp);
		debufkit.add(defhelmet);
		debufkit.add(defchestplate);
		debufkit.add(defleggings);
		debufkit.add(defboots);
		
		ItemStack invishelmet = CI.createItem(Material.LEATHER_HELMET, 1, -1, ChatColor.GOLD + "Invisible Helmet");
		invishelmet.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack invischestplate = CI.createItem(Material.LEATHER_CHESTPLATE, 1, -1, ChatColor.GOLD + "Invisible Chestplate");
		invischestplate.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack invisleggings = CI.createItem(Material.LEATHER_LEGGINGS, 1, -1, ChatColor.GOLD + "Invisible Leggings");
		invisleggings.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack invisboots = CI.createItem(Material.LEATHER_BOOTS, 1, -1, ChatColor.GOLD + "Invisible Boots");
		invisboots.addEnchantment(Enchantment.DURABILITY, 3);
		T_ItemStack invissword = new T_ItemStack(CI.createItem(Material.STONE_SWORD, 1, -1, ChatColor.GOLD + "Invisible Sword"));
		ItemStack invisbow = CI.createItem(Material.BOW, 1, -1, ChatColor.GOLD + "Invisible Bow");
		invisbow.addEnchantment(Enchantment.ARROW_KNOCKBACK, 1);
		invisbow.addEnchantment(Enchantment.ARROW_INFINITE, 1);
		ItemStack invisarrow = CI.createItem(Material.ARROW, 1, -1, ChatColor.GOLD + "Invisible Arrow");
		ItemStack invisgapple = CI.createItem(Material.GOLDEN_APPLE, 3, 0, ChatColor.GOLD + "Invisible Apple");
		ItemStack invispearl = CI.createItem(Material.ENDER_PEARL, 4, -1, ChatColor.GOLD +  "Invisible Pearl");
		Potion speedpotionnn = new Potion(PotionType.SPEED, 1);
		speedpotionnn.setSplash(true);
		ItemStack invisspeedp = speedpotionnn.toItemStack(2);
		invisspeedp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "Invisible Speed Pot"); 
		Potion healpotionnn = new Potion(PotionType.INSTANT_HEAL, 1);
		healpotionnn.setSplash(true);
		ItemStack invishealp = healpotionnn.toItemStack(1);
		invishealp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "Invisible Heal Pot");
		Potion regpotionnn = new Potion(PotionType.REGEN, 1);
		regpotionnn.setSplash(true);
		ItemStack invisregp = regpotionnn.toItemStack(1);
		invisregp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "Invisible Regen Pot");
		Potion invpotion = new Potion(PotionType.INVISIBILITY, 1);
		invpotion.setSplash(true);
		ItemStack invisinvp = invpotion.toItemStack(1);
		invisinvp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "Invisible Pot");
		invissword.addGlow();
		inviskit.add(invissword.toItemStack());
		inviskit.add(invisbow);
		inviskit.add(invisarrow);
		inviskit.add(invisgapple);
		inviskit.add(invispearl);
		inviskit.add(invisspeedp);
		inviskit.add(invishealp);
		inviskit.add(invisinvp);
		inviskit.add(invisregp);
		inviskit.add(invishelmet);
		inviskit.add(invischestplate);
		inviskit.add(invisleggings);
		inviskit.add(invisboots);
		
		ItemStack strengthhelmet = CI.createItem(Material.CHAINMAIL_HELMET, 1, -1, ChatColor.DARK_AQUA + "Strength Helmet");
		strengthhelmet.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack strengthchestplate = CI.createItem(Material.CHAINMAIL_CHESTPLATE, 1, -1, ChatColor.DARK_AQUA + "Strength Chestplate");
		strengthchestplate.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack strengthleggings = CI.createItem(Material.CHAINMAIL_LEGGINGS, 1, -1, ChatColor.DARK_AQUA + "Strength Leggings");
		strengthleggings.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack strengthboots = CI.createItem(Material.CHAINMAIL_BOOTS, 1, -1, ChatColor.DARK_AQUA + "Strength Boots");
		strengthboots.addEnchantment(Enchantment.DURABILITY, 3);
		T_ItemStack strengthsword = new T_ItemStack(CI.createItem(Material.GOLD_SWORD, 1, -1, ChatColor.DARK_AQUA + "Strength Sword"));
		ItemStack strengthbow = CI.createItem(Material.BOW, 1, -1, ChatColor.DARK_AQUA + "Strength Bow");
		strengthbow.addEnchantment(Enchantment.ARROW_KNOCKBACK, 1);
		strengthbow.addEnchantment(Enchantment.ARROW_INFINITE, 1);
		ItemStack strengtharrow = CI.createItem(Material.ARROW, 1, -1, ChatColor.DARK_AQUA + "Strength Arrow");
		ItemStack strengthgapple = CI.createItem(Material.GOLDEN_APPLE, 3, 0, ChatColor.DARK_AQUA + "Strength Apple");
		ItemStack strengthpearl = CI.createItem(Material.ENDER_PEARL, 4, -1, ChatColor.DARK_AQUA + "Strength Pearl");
		Potion speedpotioni = new Potion(PotionType.SPEED, 1);
		speedpotioni.setSplash(true);
		ItemStack strengthspeedp = speedpotioni.toItemStack(1);
		strengthspeedp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "Strength Speed Pot"); 
		Potion healpotioni = new Potion(PotionType.INSTANT_HEAL, 1);
		healpotioni.setSplash(true);
		ItemStack strengthhealp = healpotioni.toItemStack(1);
		strengthhealp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "Strength Heal Pot");
		Potion regpotioni = new Potion(PotionType.REGEN, 1);
		regpotioni.setSplash(true);
		ItemStack strengthregp = regpotioni.toItemStack(1);
		strengthregp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "Strength Regen Pot");
		strengthsword.addGlow();
		strengthkit.add(strengthsword.toItemStack());
		strengthkit.add(strengthbow);
		strengthkit.add(strengtharrow);
		strengthkit.add(strengthgapple);
		strengthkit.add(strengthpearl);
		strengthkit.add(strengthspeedp);
		strengthkit.add(strengthhealp);
		strengthkit.add(strengthregp);
		strengthkit.add(strengthhelmet);
		strengthkit.add(strengthchestplate);
		strengthkit.add(strengthleggings);
		strengthkit.add(strengthboots);
		
		ItemStack archerhelmet = CI.createItem(Material.LEATHER_HELMET, 1, -1, ChatColor.DARK_AQUA + "Archer Helmet");
		archerhelmet.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack archerchestplate = CI.createItem(Material.LEATHER_CHESTPLATE, 1, -1, ChatColor.DARK_AQUA + "Archer Chestplate");
		archerchestplate.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack archerleggings = CI.createItem(Material.LEATHER_LEGGINGS, 1, -1, ChatColor.DARK_AQUA + "Archer Leggings");
		archerleggings.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack archerboots = CI.createItem(Material.LEATHER_BOOTS, 1, -1, ChatColor.DARK_AQUA + "Archer Boots");
		archerboots.addEnchantment(Enchantment.DURABILITY, 3);
		T_ItemStack archersword = new T_ItemStack(CI.createItem(Material.WOOD_SWORD, 1, -1, ChatColor.DARK_AQUA + "Archer Sword"));
		ItemStack archerbow = CI.createItem(Material.BOW, 1, -1, ChatColor.DARK_AQUA + "Archer Bow");
		archerbow.addEnchantment(Enchantment.ARROW_KNOCKBACK, 1);
		archerbow.addEnchantment(Enchantment.ARROW_INFINITE, 1);
		archerbow.addEnchantment(Enchantment.ARROW_FIRE, 1);
		ItemStack archerarrow = CI.createItem(Material.ARROW, 1, -1, ChatColor.DARK_AQUA + "Archer Arrow");
		ItemStack archergapple = CI.createItem(Material.GOLDEN_APPLE, 3, 0, ChatColor.DARK_AQUA + "Archer Apple");
		ItemStack archerpearl = CI.createItem(Material.ENDER_PEARL, 4, -1, ChatColor.DARK_AQUA + "Archer Pearl");
		Potion speedpotioniii = new Potion(PotionType.SPEED, 1);
		speedpotioni.setSplash(true);
		ItemStack archerspeedp = speedpotioniii.toItemStack(1);
		archerspeedp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "Archer Speed Pot"); 
		Potion healpotioniii = new Potion(PotionType.INSTANT_HEAL, 1);
		healpotioni.setSplash(true);
		ItemStack archerhealp = healpotioniii.toItemStack(1);
		archerhealp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "Archer Heal Pot");
		Potion regpotioniii = new Potion(PotionType.REGEN, 1);
		regpotioni.setSplash(true);
		ItemStack archerregp = regpotioniii.toItemStack(1);
		archerregp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "Archer Regen Pot");
		archersword.addGlow();
		archerkit.add(archersword.toItemStack());
		archerkit.add(archerbow);
		archerkit.add(archerarrow);
		archerkit.add(archergapple);
		archerkit.add(archerpearl);
		archerkit.add(archerspeedp);
		archerkit.add(archerhealp);
		archerkit.add(archerregp);
		archerkit.add(archerhelmet);
		archerkit.add(archerchestplate);
		archerkit.add(archerleggings);
		archerkit.add(archerboots);
		
		ItemStack ophelmet = CI.createItem(Material.LEATHER_HELMET, 1, -1, ChatColor.GOLD + "OP Helmet");
		ophelmet.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack opchestplate = CI.createItem(Material.LEATHER_CHESTPLATE, 1, -1, ChatColor.GOLD + "OP Chestplate");
		opchestplate.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack opleggings = CI.createItem(Material.LEATHER_LEGGINGS, 1, -1, ChatColor.GOLD + "OP Leggings");
		opleggings.addEnchantment(Enchantment.DURABILITY, 3);
		ItemStack opboots = CI.createItem(Material.LEATHER_BOOTS, 1, -1, ChatColor.GOLD + "OP Boots");
		opboots.addEnchantment(Enchantment.DURABILITY, 3);
		T_ItemStack opsword = new T_ItemStack(CI.createItem(Material.DIAMOND_SWORD, 1, -1, ChatColor.GOLD + "OP Sword"));
		ItemStack oppearl = CI.createItem(Material.ENDER_PEARL, 4, -1, ChatColor.DARK_AQUA + "OP Pearl");
		Potion speedpotionii = new Potion(PotionType.SPEED, 1);
		speedpotionii.setSplash(true);
		ItemStack opspeedp = speedpotionii.toItemStack(1);
		strengthspeedp.getItemMeta().setDisplayName(ChatColor.DARK_AQUA + "OP Speed Pot"); 
		opsword.addGlow();
		opkit.add(opsword.toItemStack());
		opkit.add(oppearl);
		opkit.add(opspeedp);
		opkit.add(ophelmet);
		opkit.add(opchestplate);
		opkit.add(opleggings);
		opkit.add(opboots);
	}
} 